# ✅ SECRETS CORRETOS PARA STREAMLIT CLOUD
# Cole exatamente este formato no Streamlit Cloud > Settings > Secrets

[secrets]
DB_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
DB_DATABASE = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "Mariaana953@7334"
DB_PORT = "5432"
DATABASE_ENVIRONMENT = "supabase"

# Formato alternativo (compatibilidade)
SUPABASE_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
SUPABASE_DB = "postgres"
SUPABASE_USER = "postgres"
SUPABASE_PASSWORD = "Mariaana953@7334"
SUPABASE_PORT = "5432"
