# Configuração de Secrets para Streamlit Cloud
# Cole este conteúdo em: Advanced settings > Secrets

# Formato padrão Streamlit Cloud (DB_)
DB_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
DB_DATABASE = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "Mariaana953@7334"
DB_PORT = "5432"
DATABASE_ENVIRONMENT = "supabase"

# Formato alternativo (SUPABASE_) - para compatibilidade
SUPABASE_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
SUPABASE_DB = "postgres"  
SUPABASE_USER = "postgres"
SUPABASE_PASSWORD = "Mariaana953@7334"
SUPABASE_PORT = "5432"

# Configurações opcionais do servidor
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
