# Configuração de Secrets para Streamlit Cloud
# Cole este conteúdo em: Advanced settings > Secrets

SUPABASE_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
SUPABASE_DB = "postgres"  
SUPABASE_USER = "postgres"
SUPABASE_PASSWORD = "Mariaana953@7334"
SUPABASE_PORT = "5432"
DATABASE_ENVIRONMENT = "supabase"

# Configurações opcionais do servidor
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
