[theme]
primaryColor = "#0f4c75"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#495057"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 100

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[global]
developmentMode = false
suppressDeprecationWarnings = true
