# Configurações Supabase - Dashboard Baker
[supabase]
host = "db.lijtncazuwnbydeqtoyz.supabase.co"
password = "Mariaana953@7334"
user = "postgres"
database = "postgres"
port = "5432"

# Configurações principais do banco
[database]
DB_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
DB_PASSWORD = "Mariaana953@7334"
DB_USER = "postgres"
DB_NAME = "postgres"
DB_PORT = "5432"

# Configurações de ambiente
[environment]
ENVIRONMENT = "production"
DEBUG = false

# Configurações de segurança
[security]
SSL_MODE = "require"
CONNECTION_TIMEOUT = 30