# Configurações Supabase
SUPABASE_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
SUPABASE_PASSWORD = "Mariaana953@7334"
SUPABASE_USER = "postgres"
SUPABASE_DB = "postgres"
SUPABASE_PORT = "5432"

# Fallback para outras configs
DB_HOST = "db.lijtncazuwnbydeqtoyz.supabase.co"
DB_PASSWORD = "Mariaana953@7334"
DB_USER = "postgres"
DB_NAME = "postgres"
DB_PORT = "5432"